logging:
  level:
    root: INFO

spring:
  security:
    user:
      password: 'welkom42'

saml:
  enabled: true
  attributes:
    user: username
    email: email
  keystore:
    file_name: classpath:simple-saml.jks
    key: apollo
    password: nalle123
    user: apollo
  idp_logout_url: http://localhost:8090/simplesaml/saml2/idp/SingleLogoutService.php
  idp_metadata_url: http://localhost:8090/simplesaml/saml2/idp/metadata.php
  idp_url: http://localhost:8090/simplesaml/saml2/idp/SSOService.php
  properties:
    # debug: true
    contacts:
      technical:
        given_name: 'Support 42'
        email_address: 'support@42.nl'
  sp_id: 42-saml
  sp_base_url: http://localhost:8080
  success_url: http://localhost:8080