spring:
  security:
    user:
      password: 'welkom42'

saml:
  assertions:
    organisation: 'surfguest.nl|harvard-example.edu|vorsen.nl'
  attributes:
    user: urn:oid:user
    role: urn:oid:role
    organisation: urn:oid:organisation
  enabled: true
  idp_url: https://engine.test.surfconext.nl/authentication/idp/single-sign-on
  keystore:
    file_name: classpath:simple-saml.jks
    key: apollo
    password: nalle123
    user: apollo
  logout_url: https://engine.test.surfconext.nl/logout
  metadata_url: https://engine.test.surfconext.nl/authentication/idp/metadata
  properties:
    strict: true
    debug: true
    organization:
      name: SP Java
      displayname: SP Java Example
      url: http://sp.example.com
      lang: en
    contacts:
      technical:
        given_name: Technical Guy
        email_address: technical@example.com
      support:
        given_name: Support Guy
        email_address: support@example.com
  response_skew: 600
  roles:
    medewerker: ROLE_USER
  sp_id: urn:nl:42:saml:local:sp
  sp_base_url: http://localhost:8080/api
