spring:
  security:
    user:
      password: 'welkom42'

saml:
  enabled: true
  attributes:
    user: username
    email: email
    role: samlRole # when excluded throws an error: Could not map property.
  role_required: false
  idp_url: http://localhost:8090/simplesaml/saml2/idp/SSOService.php
  metadata_url: http://localhost:8090/simplesaml/saml2/idp/metadata.php
  keystore:
    file_name: classpath:simple-saml.jks
    key: apollo
    password: nalle123
    user: apollo
  sp_id: 42-saml
  sp_base_url: http://localhost:8080
  success_url: http://localhost:8080
  logout_url: http://localhost:8080
  expired_url: http://localhost:8080
  forbidden_url: http://localhost:8080